language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run test
branches:
  only:
    - master
addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4
before_script:
  - cp .env.travis .env
  - NODE_ENV=test npm run db:create
