language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run test
branches:
  only:
    - master
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - cp .env.travis .env
  - psql -c 'CREATE DATABASE aps7_test;' -U postgres
